# Generated by Django 4.2.2 on 2023-06-16 01:19

import carsuri.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('detail_no', models.AutoField(primary_key=True, serialize=False)),
                ('detail_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fileupload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(upload_to=carsuri.models.date_upload_to)),
            ],
            options={
                'db_table': 'fileupload',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Maker',
            fields=[
                ('maker_no', models.AutoField(primary_key=True, serialize=False)),
                ('maker_name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
            options={
                'db_table': 'maker',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('model_no', models.AutoField(primary_key=True, serialize=False)),
                ('model_name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
            options={
                'db_table': 'model',
                'managed': False,
            },
        ),
    ]
