# Generated by Django 4.2 on 2023-06-21 09:33

import carsuri.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('detail_no', models.AutoField(primary_key=True, serialize=False)),
                ('detail_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExchangeCost',
            fields=[
                ('exchange_cost_no', models.AutoField(primary_key=True, serialize=False)),
                ('cost', models.IntegerField(blank=True, null=True)),
                ('exchange', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'exchange_cost',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fileupload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(upload_to=carsuri.models.date_upload_to)),
            ],
            options={
                'db_table': 'fileupload',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Maker',
            fields=[
                ('maker_no', models.AutoField(primary_key=True, serialize=False)),
                ('maker_name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
            options={
                'db_table': 'maker',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('map_no', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('addr', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('tel', models.CharField(blank=True, max_length=13, null=True)),
            ],
            options={
                'db_table': 'map',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('model_no', models.AutoField(primary_key=True, serialize=False)),
                ('model_name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
            options={
                'db_table': 'model',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RepairCost',
            fields=[
                ('repair_cost_no', models.AutoField(primary_key=True, serialize=False)),
                ('cost', models.IntegerField(blank=True, null=True)),
                ('repair', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'repair_cost',
                'managed': False,
            },
        ),
    ]
